name: Pull Request Check

#
#   IMPORTANT TO KNOW
#
# - This workflow runs whenever new changes are pushed to an existing Pull Request
# - Runs on 'master', 'develop', 'release/*' and 'hotfix/*', 'bugfix/*' branches
#

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Generate Engagement data collections
    timeout-minutes: 30
    steps:
      - name: Generate token
        id: generate_token
        uses: navikt/github-app-token-generator@v1
        with:
          private-key: ${{ secrets.GIT_GITHUB_APP_PEM_FILE }}
          app-id: ${{ secrets.GIT_GITHUB_APP_ID }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate_token.outputs.token }}

      - name: Generate Engagements data collections
        uses: ./.github/actions/build-and-test
        with:
          githubProject: ${{ github.event.repository.name }}